#!/bin/bash
#: Title       : Dname
#: Date        : 2016-04-12
#: Author      : "Kybernetes" <correodelkybernetes@gmail.com>
#: Version     : 1.1
#: Description : Strips the directory name from provided path
#: Options     : NA

main() {
    local path=${1?"An argument is required"}
    shift $#

    case $path in
	*/*) ## Does $path contain any "/" character? 
	    printf "%s\n" "${path%/*}" ;;
	*)   ## Here we have to assume that provided path is relative and points to a file in the PWD.
	     ## However if it does not exist, we will print a dot.
	    [ -e "$path" ] && printf "%s\n" "$PWD" || echo "." ;;
    esac
}

main "$@"
