#!/bin/bash
#: Title       : Sa
#: Date        : 2016-04-08
#: Author      : "Kybernetes" <correodelkybernetes@gmail.com>
#: Version     : 1.0
#: Description : Display command-line arguments
#: Options     : N/A

main() {
    # shift $#     # Do not spare any arguments

    local pre=:  # Passed arguments delimeters
    local post=: # 

    # Print each argument on a separate line, enclosed by previous delimiters
    printf "$pre%s$post\n" "$@"
}

#
# The special parameter $@ expands to a list of all the command-line arguments, but the results differ depending on
# whether it is quoted. When quoted, it expands to the positional parameters "$1", "$2", "$3", "$4", and so on, and the
# arguments containing whitespace will be preserved. If $@ is unquoted, splitting will occur wherever there is
# whitespace.
main "$@"
