#!/bin/bash
#: Title       : Test
#: Date        : 2016-05-30
#: Author      : "Kybernetes" <correodelkybernetes@gmail.com>
#: Version     : 1.0
#: Description : Convert Word to Uppercase test
#: Options     : N/A

## Inclusions
. "${0%/*}/upword1" || exit 1

main() {
    shift $#

   upword " :Test string:"
   upword "Artigas ñemoñaré, by Nelson Caula"
   upword '/!\ Additional test string /!\'

   printf "\n%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n\n"
    . "${0%/*}/upword2" || exit 1

    upword " :tesT String:"
    upword "Artigas Ñeoñaré, by Nelson Caula"
    upword '/!\ Additional test string /!\'

}

## Run!
main "$@"
