#!/bin/bash
#: Title       : Isvalidip
#: Date        : 2016-05-15
#: Author      : "Kybernetes" <correodelkybernetes@gmail.com>
#: Version     : 1.0
#: Description : Check argument for valid dotted-quad IP address
#: Options     : NA

isvalidip() { #@ USAGE: isvalidip '[ DOTTED-QUAD ]'
    ## Funtion header
    ## FUNCNAME contains the name of any currently-executing shell function
    local dttd_quad="${1?$FUNCNAME: An argument is required}"
    shift $#
    
    case $dttd_quad in
	## Reject the following:
	## * Empty dttd_quad;
	## * Anything other than digits and dots;
	## * Anything not ending in a digit
	"" | *[^0-9.]* | *[^0-9] ) return 1 ;;
    esac
    
    ## Change IFS to a dot, but only in this function
    local IFS=.
    
    ## Place the IP addresss into the positional parameters;
    ## After word splitting each element becomes a parameter
    set -- $dttd_quad
    [ $# -eq 4 ] && ## Must be four parameters
                    ## Each must be less than 256
    ## A default of 666 (which is invalid) is used if a parameter is empty
    ## All four parameters must pass the test
    [ ${1:-666} -le 255 ] && [ ${2:-666} -le 255 ] &&
    [ ${3:-666} -le 255 ] && [ ${4:-666} -le 255 ]
}
## NOTE: Formats other than dotted quads can be valid IP addresses, as in 127.1, 216.239.10085 and 3639551845.
