#!/bin/bash
#: Title       : Checkarg
#: Date        : 2016-04-12
#: Author      : "Kybernetes" <correodelkybernetes@gmail.com>
#: Version     : 1.0
#: Description : Exit If Parameters Are Unset Or Empty
#: Options     : NA

main() {
    ## ":" Is the null command: the command does nothing beyond expanding arguments and performing any specified
    ## redirections.  A zero exit code is returned.

    ## Check for unset arguments
    : ${1?An argument is required} \
      ${2?Two arguments are required}

    ## Check for empty arguments
    : ${1:?A non-empty argument is required} \
      ${2:?Two non-empty arguments are required}

    shift $#

    echo "Thank you."
}

main "$@"
