#!/bin/bash
#: Title       : Test
#: Date        : 2016-05-21
#: Author      : "Kybernetes" <correodelkybernetes@gmail.com>
#: Version     : 1.0
#: Description : Traversing a string & testing performance
#: Options     : N/A

traverse1() {
    local string=${1:?"$FUNCNAME: Missing argument"}
    shift $#
    
    local char= temp=

    while [ -n "$string" ]; do
	temp=${string#?}       ## Everything but the first char
	char=${string%"$temp"} ## First char (don't forgate quotation)
	printf "%c " "$char"   ## Do something with it
	string=$temp           ## Assign truncanted vaule to var
    done
}
traverse2() {
   local string=${1:?"$FUNCNAME: Missing argument"}
   shift $#
   
   local char=""

   ## Trying to do the same thing but with printf
   while [ -n "$string" ]; do
       printf -v char "%c" "$string" ## First character of a string can
       printf "%c " "$char"          ## also be obtained with printf
       string=${string#"$char"}      ## Quotation is needed to avoid reinterp. of special chars
   done
}
main() {
    shift $#
    time traverse1 '\¡Coplas y recoplas de constantinopla!'
    time traverse2 '\¡Coplas y recoplas de constantinopla!'
}

main "$@"
